spring:
  application:
    name: ho-gateway

server:
  port: 1112

zuul:
  prefix: /api

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka

ribbon:
  ConnectTimeout: 500        #ribbon链接超时时长
  ReadTimeout: 5000           #ribbon读取超时时长
  MaxAutoRetries: 0           #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
