spring:
  application:
    name: ho-gateway

server:
  port: 10011

zuul:
  prefix: /api
  routes:
    item-service: /item/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka

ribbon:
  ConnectTimeout: 500        #ribbon链接超时时长
  ReadTimeout: 5000           #ribbon读取超时时长
  MaxAutoRetries: 0           #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
