spring:
  datasource:
    url: jdbc:mysql://localhost:3306/horizon?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: item-service
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: ho.item.exchange
    publisher-confirms: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka
