server:
  port: 10010
spring:
  application:
    name: ho-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka
    fetch-registry: false
    register-with-eureka: false