server:
  port: 1111
spring:
  application:
    name: ho-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
    fetch-registry: false
    register-with-eureka: false